### ISSUE TITLE
UnrealizedPnL is not correct after upgrading version 10.0.0

### ISSUE THREAD

**Issue by dante1989** [JKorf/Binance.Net#1400]
Position is opened for ETHUSD 
 
Dim BinanceFuturesPositions_CheckBalance  = Await clientBinance.CoinFuturesApi.Account.GetPositionInformationAsync
                                For Each LongShortPosition In BinanceFuturesPositions_CheckBalance.Data

                                    If LongShortPosition.Symbol = "ETHUSD" Then

                                      Dim  Balance_UnrealizedPnL = LongShortPosition.UnrealizedPnL
                                    End IF
                                 Next

Version 9.12.0 - 16 Jul 2024: Balance_UnrealizedPnL has a valid value > 0
Version 10.0.0 - 27 Jul 2024: Balance_UnrealizedPnL = 0

**Comment by JKorf** [comment]
Hi, fixed in the latest version. CoinFutures returns `UnRealizedProfit` instead of `UnrealizedProfit`. Json.Net converter allows this, but System.Text.Json doesn't (by default). I've fixed this in latest version, and updated tests to check for capitalization

**Comment by dante1989** [comment]
After using the newest version Version 10.1.0 - 07 Aug 2024, i have still the same problem. 
When i come back Version 9.12.0 again. It is ok.

**Comment by JKorf** [comment]
Ah you're right. Another case to add in my tests (forgot the JsonInclude attribute). I've tested it and it works with the latest version 10.1.1

**Comment by dante1989** [comment]
I have sent the donation, thank you
Could you tell us why are you choosing system.text.json?

**Comment by JKorf** [comment]
Thanks, appreciated. 

Sure, mainly 2 reasons:
1. System.Text.Json is faster
2. When all libraries have been migrated (long term) the Newtonsoft.Json package can be removed as reference and I think the less third party packages the better. I'd prefer Microsoft packages over third party packages.

**Comment by dante1989** [comment]
Thank you
