### ISSUE TITLE
AggregateException in BaseSocket when retrying connect

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Binance.Net#167]
07:31:43.36[155]DEBUG:[Binance] API: 2018/12/12 07:31:43:362 | Info | Socket 220 error: System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.OnDataRead(IAsyncResult result)
07:31:43.36[155]DEBUG:[Binance] API: 2018/12/12 07:31:43:363 | Info | Socket 220 Connection lost, will try to reconnect
07:31:52.08[113]DEBUG:[Binance] API: 2018/12/12 07:31:52:087 | Info | Socket 188 error: System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.OnDataRead(IAsyncResult result)
07:31:52.08[113]DEBUG:[Binance] API: 2018/12/12 07:31:52:087 | Info | Socket 188 Connection lost, will try to reconnect
07:31:56.02[46]DEBUG:[Binance] API: 2018/12/12 07:31:56:025 | Info | Socket 220 reconnected after 00:00:12.6623931
07:31:56.02[46]DEBUG:[Binance] API: 2018/12/12 07:31:56:026 | Info | Socket 220 successfully resubscribed
07:31:56.45[239]DEBUG:[Binance] API: 2018/12/12 07:31:56:455 | Info | Socket 186 error: System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.OnDataRead(IAsyncResult result)
07:31:56.45[239]DEBUG:[Binance] API: 2018/12/12 07:31:56:455 | Info | Socket 186 Connection lost, will try to reconnect
07:31:58.46[263]DEBUG:[Binance] API: 2018/12/12 07:31:58:459 | Info | Socket 188 reconnected after 00:00:06.3713795
07:31:58.46[263]DEBUG:[Binance] API: 2018/12/12 07:31:58:460 | Info | Socket 188 successfully resubscribed
07:32:16.45[94]DEBUG:[Binance] API: 2018/12/12 07:32:16:458 | Info | Socket 186 Connection lost, will try to reconnect
07:32:17.25[239]DEBUG:[Binance] API: 2018/12/12 07:32:17:255 | Info | Socket 191 error: System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.OnDataRead(IAsyncResult result)
07:32:17.25[239]DEBUG:[Binance] API: 2018/12/12 07:32:17:256 | Info | Socket 191 Connection lost, will try to reconnect
07:32:25.56[2]FATAL:UnobservedTaskException: AggregateException:
AggregateException:
Exception:The socket is connecting, cannot connect again!:   at SuperSocket.ClientEngine.TcpClientSession.Connect(EndPoint remoteEndPoint)
   at CryptoExchange.Net.Sockets.BaseSocket.<Connect>b__74_5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at CryptoExchange.Net.Sockets.BaseSocket.<Connect>d__74.MoveNext()

**Comment by NektoDron** [comment]
this bug happens on 4.0.1 and not happens on version before 4.0.0

**Comment by NektoDron** [comment]
4.0.2 has the same problem:
14:47:09.02[121]DEBUG:[Binance] API: 2018/12/12 14:47:09:022 | Info | Socket 98 error: System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.OnDataRead(IAsyncResult result)
14:47:09.02[121]DEBUG:[Binance] API: 2018/12/12 14:47:09:027 | Info | Socket 98 Connection lost, will try to reconnect
14:47:15.32[83]DEBUG:[Binance] API: 2018/12/12 14:47:15:322 | Info | Socket 98 reconnected after 00:00:06.2935093
14:47:15.32[83]DEBUG:[Binance] API: 2018/12/12 14:47:15:324 | Info | Socket 98 successfully resubscribed
14:47:55.13[9]DEBUG:[Binance] API: 2018/12/12 14:47:55:138 | Info | Socket 1 error: System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.OnDataRead(IAsyncResult result)
14:47:55.13[9]DEBUG:[Binance] API: 2018/12/12 14:47:55:138 | Info | Socket 1 Connection lost, will try to reconnect
14:47:56.19[20]DEBUG:[Binance] API: 2018/12/12 14:47:56:196 | Info | Socket 90 error: System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.OnDataRead(IAsyncResult result)
14:47:56.20[20]DEBUG:[Binance] API: 2018/12/12 14:47:56:200 | Info | Socket 90 Connection lost, will try to reconnect
14:48:04.75[73]DEBUG:[Binance] API: 2018/12/12 14:48:04:751 | Info | Socket 1 reconnected after 00:00:09.6119774
14:48:04.75[73]DEBUG:[Binance] API: 2018/12/12 14:48:04:751 | Info | Socket 1 successfully resubscribed
14:48:04.78[9]DEBUG:[Bitfinex] API: 2018/12/12 14:48:04:780 | Info | Socket 18 Connection lost, will try to reconnect
14:48:10.17[73]DEBUG:[Bitfinex] API: 2018/12/12 14:48:10:179 | Info | Socket 18 reconnected after 00:00:05.3985010
14:48:10.25[73]DEBUG:[Bitfinex] API: 2018/12/12 14:48:10:251 | Info | Socket 18 successfully resubscribed
14:48:16.20[83]DEBUG:[Binance] API: 2018/12/12 14:48:16:206 | Info | Socket 90 Connection lost, will try to reconnect
14:48:18.05[100]DEBUG:[Binance] API: 2018/12/12 14:48:18:055 | Info | Socket 107 error: System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.OnDataRead(IAsyncResult result)
14:48:18.05[100]DEBUG:[Binance] API: 2018/12/12 14:48:18:056 | Info | Socket 107 Connection lost, will try to reconnect
14:48:22.03[2]FATAL:UnobservedTaskException: AggregateException:
AggregateException:
Exception:The socket is connected, you needn't connect again!:   at SuperSocket.ClientEngine.TcpClientSession.Connect(EndPoint remoteEndPoint)
   at CryptoExchange.Net.Sockets.BaseSocket.<Connect>b__74_5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at CryptoExchange.Net.Sockets.BaseSocket.<Connect>d__74.MoveNext()


14:48:24.33[73]DEBUG:[Binance] API: 2018/12/12 14:48:24:337 | Info | Socket 107 reconnected after 00:00:06.2810298
14:48:24.33[73]DEBUG:[Binance] API: 2018/12/12 14:48:24:338 | Info | Socket 107 successfully resubscribed
14:48:25.55[101]DEBUG:[Binance] API: 2018/12/12 14:48:25:554 | Info | Socket 84 error: System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.OnDataRead(IAsyncResult result)
14:48:25.55[101]DEBUG:[Binance] API: 2018/12/12 14:48:25:554 | Info | Socket 84 Connection lost, will try to reconnect
14:48:45.55[34]DEBUG:[Binance] API: 2018/12/12 14:48:45:558 | Info | Socket 84 Connection lost, will try to reconnect
14:48:56.67[22]DEBUG:[Binance] API: 2018/12/12 14:48:56:671 | Info | Socket 84 reconnected after 00:00:31.1166315
14:48:56.67[22]DEBUG:[Binance] API: 2018/12/12 14:48:56:672 | Info | Socket 84 successfully resubscribed
14:49:24.81[95]DEBUG:[Bitfinex] API: 2018/12/12 14:49:24:817 | Info | Socket 38 Connection lost, will try to reconnect
14:49:30.21[22]DEBUG:[Bitfinex] API: 2018/12/12 14:49:30:218 | Info | Socket 38 reconnected after 00:00:05.4009966
14:49:30.31[22]DEBUG:[Bitfinex] API: 2018/12/12 14:49:30:310 | Info | Socket 38 successfully resubscribed
14:50:22.12[198]DEBUG:[Bitfinex] API: 2018/12/12 14:50:22:125 | Info | Socket 17 Connection lost, will try to reconnect
14:50:25.02[225]DEBUG:[Bitfinex] API: 2018/12/12 14:50:25:027 | Info | Socket 19 Connection lost, will try to reconnect
14:50:27.53[24]DEBUG:[Bitfinex] API: 2018/12/12 14:50:27:530 | Info | Socket 17 reconnected after 00:00:05.4039921
14:50:27.60[24]DEBUG:[Bitfinex] API: 2018/12/12 14:50:27:602 | Info | Socket 17 successfully resubscribed
14:50:30.36[203]DEBUG:[Bitfinex] API: 2018/12/12 14:50:30:361 | Info | Socket 19 reconnected after 00:00:05.3336096
14:50:30.44[203]DEBUG:[Bitfinex] API: 2018/12/12 14:50:30:440 | Info | Socket 19 successfully resubscribed
14:52:20.07[95]DEBUG:[Bitfinex] API: 2018/12/12 14:52:20:074 | Info | Socket 20 Connection lost, will try to reconnect
14:52:25.48[22]DEBUG:[Bitfinex] API: 2018/12/12 14:52:25:480 | Info | Socket 20 reconnected after 00:00:05.4044910
14:52:25.55[22]DEBUG:[Bitfinex] API: 2018/12/12 14:52:25:552 | Info | Socket 20 successfully resubscribed
14:53:50.12[875]DEBUG:[Bitfinex] API: 2018/12/12 14:53:50:127 | Info | Socket 37 Connection lost, will try to reconnect
14:53:55.59[35]DEBUG:[Bitfinex] API: 2018/12/12 14:53:55:592 | Info | Socket 37 reconnected after 00:00:05.4638918
14:53:55.66[35]DEBUG:[Bitfinex] API: 2018/12/12 14:53:55:666 | Info | Socket 37 successfully resubscribed

**Comment by NektoDron** [comment]
In 4.0.3
1:28:08.08[98]DEBUG:[Bittrex] API: 2018/12/18 11:28:08:084 | Info | Socket 49 Connection lost, will try to reconnect
11:28:08.18[105]DEBUG:[Bittrex] API: 2018/12/18 11:28:08:183 | Info | Socket 67 Connection lost, will try to reconnect
11:28:14.24[2]FATAL:UnobservedTaskException: AggregateException:
NullReferenceException:Object reference not set to an instance of an object.:   at CryptoExchange.Net.Sockets.BaseSocket.Reset()
   at CryptoExchange.Net.SocketClient.<>c__DisplayClass28_0.<SocketOnClose>b__0()
   at System.Threading.Tasks.Task.Execute()

11:36:08.94[5278]INFO :Server time was updated to '18-12-2018 08:36:07.176 +03:00 kind:Local' from '18-12-2018 08:36:07.477 +03:00 kind:Local' with no check. TimeDiff: -03:00:01.7687032
11:38:23.08[1]DEBUG:MainWindow deactivated
11:38:24.49[2]FATAL:UnobservedTaskException: AggregateException:
NullReferenceException:Object reference not set to an instance of an object.:   at CryptoExchange.Net.Sockets.BaseSocket.Reset()
   at CryptoExchange.Net.SocketClient.<>c__DisplayClass28_0.<SocketOnClose>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by JKorf** [comment]
Hm, I've pushed a new version of CryptoExchange.Net, v2.0.4, could you update to that and check if it is resolved?

**Comment by NektoDron** [comment]
No, it doesn't help. The same exception remains.

**Comment by NektoDron** [comment]
22:32:24.13[69048]DEBUG:[Bitfinex] API: 2018/12/20 22:32:24:136 | Info | Socket 39 reconnected after 00:00:05.4029409
22:32:24.27[85647]DEBUG:[Bitfinex] API: 2018/12/20 22:32:24:273 | Info | Socket 39 Connection lost, will try to reconnect
22:32:24.38[79584]DEBUG:[Bitfinex] API: 2018/12/20 22:32:24:382 | Info | Socket 2 reconnected after 00:00:05.3999422
22:32:24.52[85655]DEBUG:[Bitfinex] API: 2018/12/20 22:32:24:521 | Info | Socket 2 Connection lost, will try to reconnect
22:32:29.74[80069]DEBUG:[Bitfinex] API: 2018/12/20 22:32:29:743 | Info | Socket 39 reconnected after 00:00:05.4689161
22:32:29.87[80068]DEBUG:[Bitfinex] API: 2018/12/20 22:32:29:874 | Info | Socket 2 reconnected after 00:00:05.3519608
22:32:29.89[84937]DEBUG:[Bitfinex] API: 2018/12/20 22:32:29:893 | Info | Socket 39 Connection lost, will try to reconnect
22:32:29.99[84937]DEBUG:[Bitfinex] API: 2018/12/20 22:32:29:995 | Info | Socket 2 Connection lost, will try to reconnect
22:32:35.38[69048]DEBUG:[Bitfinex] API: 2018/12/20 22:32:35:386 | Info | Socket 39 reconnected after 00:00:05.4919072
22:32:35.38[11093]DEBUG:[Bitfinex] API: 2018/12/20 22:32:35:386 | Info | Socket 2 reconnected after 00:00:05.3909459
22:32:35.60[85831]FATAL:UnhandledException: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at CryptoExchange.Net.Sockets.SocketSubscription.ResetEvents()
   at CryptoExchange.Net.SocketClient.<>c__DisplayClass20_0.<CreateSocket>b__0()
   at CryptoExchange.Net.Sockets.BaseSocket.Handle(List`1 handlers)
   at CryptoExchange.Net.Sockets.BaseSocket.<Connect>b__75_2(Object o, EventArgs s)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at WebSocket4Net.WebSocket.FireClosed()
   at WebSocket4Net.WebSocket.OnClosed()
   at SuperSocket.ClientEngine.ClientSession.OnClosed()
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.Close()
   at WebSocket4Net.Command.Close.ExecuteCommand(WebSocket session, WebSocketCommandInfo commandInfo)
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.OnDataRead(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Security._SslStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
   at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
   at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
22:32:35.60[1]DEBUG:OnAppExited

**Comment by NektoDron** [comment]
and once more...
22:50:35.47[2]FATAL:UnobservedTaskException: AggregateException:
AggregateException:
Exception:The socket is connecting, cannot connect again!:   at SuperSocket.ClientEngine.TcpClientSession.Connect(EndPoint remoteEndPoint)
   at CryptoExchange.Net.Sockets.BaseSocket.<Connect>b__74_5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at CryptoExchange.Net.Sockets.BaseSocket.<Connect>d__74.MoveNext()


22:50:40.90[2]FATAL:UnobservedTaskException: AggregateException:
AggregateException:
Exception:The socket is connecting, cannot connect again!:   at SuperSocket.ClientEngine.TcpClientSession.Connect(EndPoint remoteEndPoint)
   at CryptoExchange.Net.Sockets.BaseSocket.<Connect>b__74_5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at CryptoExchange.Net.Sockets.BaseSocket.<Connect>d__74.MoveNext()

**Comment by JKorf** [comment]
Hi, should be fixed in latest (v4.0.4). Sorry, I've been busy with the holidays and all.

**Comment by cicaglisa80** [comment]
I did try your latest version yesterday and it still crashes with the same AggregateException. It takes some times but eventually it happens after 5 mins of running.

**Comment by TSLabPRO** [comment]
The new version works fine for me.

**Comment by JKorf** [comment]
@cicaglisa80 Could you verify you're on v4.0.4 since @TSLabPRO says it works. If there is still an issue could you paste new debug logging of the exception?

**Comment by JKorf** [comment]
@NektoDron Is the latest version okay for you?

**Comment by NektoDron** [comment]
@JKorf It works fine, there is no reconnection problem for two weeks.

**Comment by JKorf** [comment]
Great, I'll close this issue then. Let me know if anything comes up.
