### ISSUE TITLE
Error upon calling GetExchangeInfoAsync Method

### ISSUE THREAD

**Issue by icymaru** [JKorf/Binance.Net#312]
There's an error when calling the method with the error message:
**"Error deserializing data"**

**Comment by bajtekem** [comment]
Same here. Binance sends valid data but data being serialized is somehow corrupted.

**Comment by kayahasa** [comment]
same. Please fix it asap.

**Comment by TahaBerkay** [comment]
Getting the same error and blocking all stuff. Please take a look at that.

**Comment by faztecnyk** [comment]
same here ..

**Comment by swAucxis** [comment]
+1

**Comment by bajtekem** [comment]
As a workaround you can get exchange data with HttpClient and serialize it manually. The problem is on Binance side. Response is malformed.

**Comment by kayahasa** [comment]
if the problem is in binance side, how you can serialize it manually correctly?

**Comment by kayahasa** [comment]
Hello JKorf,

I have investigated the problem and fixed it. 
Please just make change in SymbolFilterConverter.cs at line 72 to change "limit" to "maxNumOrders".

With the new release, binance has changed that parameter name to "maxNumOrders".

İt is tested on local.
Thanks

**Comment by JKorf** [comment]
Hi everyone, I've pushed an update for this to Nuget. The fix was indeed as easy as @kayahasa already provided. Version 5.0.10 should be available in a few minutes. (alpha will follow soon after).

**Comment by CryptoClint78** [comment]
Thanks JKorf, Binance.Net is the nuts!

**Comment by Chimerique** [comment]
Seems to be the same problem for GetOpenPositions

**Comment by Chimerique** [comment]
After a little digging seems to be receiving from Binance (test futures) the value "inf" for the decimal property BinanceFuturesPosition.MaxNotionalValue

**Comment by icymaru** [comment]
It's fixed now in the new version. Thanks!

Awesome library btw :)

**Comment by eros1453** [comment]
Hi
I'm still getting MaxNumberOrders Null value exeption.
Received data is like this:

"timezone":"UTC",
 "serverTime":1588499325223,
 "rateLimits":[{
   "rateLimitType":"REQUEST_WEIGHT",
   "interval":"MINUTE",
   "intervalNum":1,
   "limit":2400},
   {"rateLimitType":"ORDERS",
	"interval":"MINUTE",
	"intervalNum":1,"limit":1200}],
 "exchangeFilters":[],
 "symbols":[
 {
   "symbol":"BTCUSDT",
   "status":"TRADING",
   "maintMarginPercent":"2.5000",
   "requiredMarginPercent":"5.0000",
   "baseAsset":"BTC",
   "quoteAsset":"USDT",
   "pricePrecision":2,
   "quantityPrecision":3,
   "baseAssetPrecision":8,
   "quotePrecision":8,
   "filters":[
    {"minPrice":"0.01","maxPrice":"100000","filterType":"PRICE_FILTER","tickSize":"0.01"},
	{"stepSize":"0.001","filterType":"LOT_SIZE","maxQty":"1000","minQty":"0.001"},
	{"stepSize":"0.001","filterType":"MARKET_LOT_SIZE","maxQty":"2775.517","minQty":"0.001"},
	{"limit":0,"filterType":"MAX_NUM_ORDERS"},
	{"limit":0,"filterType":"MAX_NUM_ALGO_ORDERS"},
	{"multiplierDown":"0.7000","multiplierUp":"1.3000","multiplierDecimal":"4","filterType":"PERCENT_PRICE"}],
   "orderTypes":["LIMIT","MARKET","STOP","STOP_MARKET","TAKE_PROFIT","TAKE_PROFIT_MARKET"],
   "timeInForce":["GTC","IOC","FOK","GTX"]},
