### ISSUE TITLE
TradeRulesBehaviour.AutoComply / Spot.Order.PlaceOrder 'stopPrice' not floored correctly

### ISSUE THREAD

**Issue by ichihaifu** [JKorf/Binance.Net#585]
```C#
BinanceClient.SetDefaultOptions(new BinanceClientOptions()
{
	ApiCredentials = new ApiCredentials(APIKEY, APISECRET),
	TradeRulesBehaviour = TradeRulesBehaviour.AutoComply,
	LogVerbosity = LogVerbosity.Debug,
	LogWriters = new List<TextWriter> { Console.Out }
});

using (var client = new BinanceClient())
{
	string COINPAIR = "MBLUSDT";
	int Buy = 10;
	var Current = client.Spot.Market.GetPrice(COINPAIR);
	var Price = Current.Data.Price;
	decimal Step = 0.0000033333333333333333333333M;
	client.Spot.Order.PlaceOrder(
		COINPAIR,
		Binance.Net.Enums.OrderSide.Buy,
		Binance.Net.Enums.OrderType.StopLossLimit,
		Buy * Price,
		null,
		null,
		Price + Step,
		Binance.Net.Enums.TimeInForce.GoodTillCancel,
		Price + Step
	);
};
```
Results in 
```
2021/02/07 16:57:53:970 | Binance    | Info | Trade rules updated
2021/02/07 16:57:53:971 | Binance    | Info | Quantity clamped from 0.01760000 to 1 based on lot size filter
2021/02/07 16:57:53:971 | Binance    | Info | price floored from 0.0017633333333333333333333333 to 0.001763 based on price filter
2021/02/07 16:57:53:971 | Binance    | Info | Stop price floored from 0.0017633333333333333333333333 to 0.001763 based on price filter
2021/02/07 16:57:53:971 | Binance    | Info | Quantity clamped from 1 to 5673 based on min notional filter
2021/02/07 16:57:53:971 | Binance    | Debug | [56] Creating request for https://api.binance.com/api/v3/order
2021/02/07 16:57:53:972 | Binance    | Debug | [56] Sending POST signed request to https://api.binance.com/api/v3/order with request body price=0.001763&quantity=5673&recvWindow=5000&side=BUY&signature=<redacted>&stopPrice=0.0017633333333333333333333333&symbol=MBLUSDT&timeInForce=GTC&timestamp=1612709875187&type=STOP_LOSS_LIMIT
2021/02/07 16:57:54:214 | Binance    | Debug | [56] Error received: {"code":-1100,"msg":"Illegal characters found in parameter 'stopPrice'; legal range is '^([0-9]{1,20})(\\.[0-9]{1,20})?$'."}
```

As you can see, `stopPrice` is not clamped correctly for the POST message despite log indicating having done that. Have I done something wrong or is there a bug in `TradeRulesBehaviour.AutoComply`?

**Comment by ichihaifu** [comment]
Maybe related to https://github.com/JKorf/Binance.Net/issues/515?

**Comment by JKorf** [comment]
Hi, thanks for the report. Indeed related. It should be fixed in 6.8.0.

**Comment by Temppus** [comment]
This is probably still not fixed for BinanceFuturesBatchOrder when using PlaceMultipleOrdersAsync API. I am getting 

```
}, {
  "code" : -1111,
  "msg" : "Precision is over the maximum defined for this asset."
} ]
```

At version 6.10.
