### ISSUE TITLE
SubscribeToKlineUpdatesAsync limit

### ISSUE THREAD

**Issue by erdalcolak** [JKorf/Binance.Net#835]
Hi,

Thank you so much for this great resource.
I am getting 226 symbol data from Kline.
While I was able to get all the data from version 6.13.6, I updated to the new version and now in 7.0.1 it can't.
I also use "SubscribeToSymbolMiniTickerUpdatesAsync" and "SubscribeToKlineUpdatesAsync". In my tests with SubscribeToSymbolMiniTickerUpdatesAsync, I can get 188 symbol data and I tried 189 symbols and it gave an error. Is there any limit.

Error
Event Type Moniker	Event	Time	Duration	Thread
2021.08.15 04:22:32:628 | Information | Binance    | Socket 2 closed 	18.80s		

` 
---Working
_socketClient.Spot.SubscribeToSymbolMiniTickerUpdatesAsync(_coinList.Take(188), data =>{ }); _socketClient.Spot.SubscribeToKlineUpdatesAsync(_coinList.Take(50), _intervalList, data =>{ }); 

--it gave error
_socketClient.Spot.SubscribeToSymbolMiniTickerUpdatesAsync(_coinList, data =>{ });
 _socketClient.Spot.SubscribeToKlineUpdatesAsync(_coinList, _intervalList, data =>{ }); 

`
Thankyou

**Comment by JKorf** [comment]
Hi, I've released a new version in which the socket connection performance should be improved, can you try again with the latest?

**Comment by erdalcolak** [comment]
Hi, I tried with new version.Problem is still. Multiple socket connection solved my problem.

**Comment by alessandroparma** [comment]
Ciao Erdal, could you be so kind to develop more on your phrase: Multiple socket connection solved my problem.

could you past the code? I am trying to get klines for all open markets (around 2600) and getting the following message: [InvalidOperationError] Message to send exceeds the max server message size (4000 bytes). Split the request into batches to keep below this limit

I hav also increased the response time to 1 minute but still getting the same message.
